name: Deploy to ECS with OIDC

on:
  push:
    branches: ["main"]

permissions:
  id-token: write      # Needed for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout repo code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS credentials using OIDC (NO ACCESS KEYS)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-ecs-deploy-role
          aws-region: eu-central-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build & Push Docker Image
      - name: Build & Push Docker Image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: eu-central-1
          ECR_REPO: ardin-ecs-demo
        run: |
          # Generate timestamp tag
          IMAGE_TAG=$(date +%s)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          echo "Building Docker image..."
          docker build -t $ECR_REPO:$IMAGE_TAG ./app

          echo "Tagging image with timestamp and latest..."
          docker tag $ECR_REPO:$IMAGE_TAG \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

          docker tag $ECR_REPO:$IMAGE_TAG \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

          echo "Pushing images to ECR..."
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

      # Force ECS Service to Redeploy with the updated :latest image
      - name: Force ECS redeployment
        run: |
          aws ecs update-service \
            --cluster ardin-ecs-cluster \
            --service nana-ecs-service \
            --force-new-deployment
